### ISSUE TITLE
401 Invalid signature

### ISSUE THREAD

**Issue by ppeczek** [seanfisher/angular-oauth1-client#2]
Anytime I get to change authorize token to access token I get alert with message - "Invalid signature". I wonder if it's lib's error.

**Comment by ppeczek** [comment]
The library creates wrong signature for getting access token. Working on it.

**Comment by ppeczek** [comment]
Made few fixes, now should work. Please, check it.

**Comment by seanfisher** [comment]
I just pushed some updates and merged #4. Will you confirm that everything is working as expected?

**Comment by ppeczek** [comment]
Changes in code seems to fix bugs, but I cannot test it. In fact the issue is outdated. I will reopen it if any problem occurs.
